version: '3'
services:
  web:
    build: ./docker/web
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/tmp
      - .:/var/www:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - ROOT=/var/www
    links:
      - "app"
